#pragma config(Sensor, dgtl11, sonar,          sensorSONAR_inch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port5,           teleMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		nVolume = 4;
//Sound Files
		playSoundFile("Begin.wav");
		playSoundFile("Nyan1.wav");
		playSoundFile("Nyan2.wav");

	wait1Msec(1000);

//Experimental



	while(1 == 1)
	{
		while(SensorValue[sonar] > 30)
		{
			motor[rightMotor] = 69;
			motor[leftMotor] = 69;
		}

		while(SensorValue[sonar] < 30)
		{
			motor[leftMotor] = 0;
		  motor[rightMotor] = -127;


		}
	}
}
