#pragma config(Sensor, dgtl11, sonarSensor,    sensorSONAR_inch)
#pragma config(Motor,  port1,           frontRight,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           teleMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          frontLeft,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int turnVar  = 0;

	while (1 == 1)
	{
		if(vexRT[Btn8R] == 1)
		{
			turnVar = 1;
		}
		if(vexRT[Btn8L] == 1)
		{
			turnVar = 2;
		}

		switch (turnVar)
		{
			case 1:
			while(vexRT[Btn8R] != 1)
			{

			motor[frontLeft] = 100;
			motor[frontRight] = 100;
			motor[backLeft] = 100;
			motor[frontRight] = 100;
			}
						turnVar = 1;
				break;

			case 2:
			while(vexRT[Btn8L] != 1)
			{
			motor[frontLeft] = -100;
			motor[frontRight] = -100;
			motor[backLeft] = -100;
			motor[backRight] = -100;
			}
				turnVar = 2;
				break;

			default:
			while (1 == 1)
	{
		//Left Motors
	motor[backLeft] = vexRT[Ch3];
	motor[frontLeft] = vexRT[Ch3];
	//Right Motors
	motor[backRight] = vexRT[Ch2];
	motor[frontRight] = vexRT[Ch2];

		//Telescoping
		if(vexRT[Btn5U] == 1)
		{
			//Raises Claw: Capped at 1/4 Speed
			motor[teleMotor] = 127;
		}
		else if(vexRT[Btn6U] == 1)
		{
			//Lowers Claw: Capped at 1/4 Speed
			motor[teleMotor] = -127;
		}
		else
		{
			motor[teleMotor] = 0;
		}

		//Claw
		if(vexRT[Btn5D] == 1)
		{
			//Opens Claw
			motor[clawMotor] = 100;
		}
		else if(vexRT[Btn6D] == 1)
		{
			//Closes Claw
			motor[clawMotor] = -100;
		}
		else
		{
			motor[clawMotor] = 0;
		}
	}
		}
	}



}
